package com.mycompany.registropasajero;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 * @author 51948
 */
public class Registro_Pasajero extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Pasajero
     */
    private String items;    

    public Registro_Pasajero() {
        initComponents();
        items = "";        
        jTextFieldNombres.setText("");
      
        jComboBoxTipoDocumento.setSelectedIndex(0);
        jTextFieldNDocumento.setText("");
        jRadioButtonMasculino.getText();
        jComboBoxOrigen.setSelectedIndex(0);
        jComboBoxDestino.setSelectedIndex(0);
        jListCalidadServicio.getSelectedValue();
        jRadioButtonPiso1.getText();
        jCheckBoxAudifonos.setSelected(false);
        jCheckBoxManta.setSelected(false);
        jCheckBoxRevistas.setSelected(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        buttonGroupPiso = new javax.swing.ButtonGroup();
        jTitulo = new javax.swing.JLabel();
        jDatosPersonales = new javax.swing.JLabel();
        jNombres = new javax.swing.JLabel();
        jTipoDocumento = new javax.swing.JLabel();
        jNDocumento = new javax.swing.JLabel();
        jGenero = new javax.swing.JLabel();
        jTextFieldNombres = new javax.swing.JTextField();
        jTextFieldNDocumento = new javax.swing.JTextField();
        jComboBoxTipoDocumento = new javax.swing.JComboBox<>();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jRadioButtonFemenino = new javax.swing.JRadioButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jServicioAdicional = new javax.swing.JLabel();
        jCheckBoxAudifonos = new javax.swing.JCheckBox();
        jCheckBoxManta = new javax.swing.JCheckBox();
        jCheckBoxRevistas = new javax.swing.JCheckBox();
        jRadioButtonPiso1 = new javax.swing.JRadioButton();
        jRadioButtonPiso2 = new javax.swing.JRadioButton();
        jPiso = new javax.swing.JLabel();
        jOrigen = new javax.swing.JLabel();
        jDestino = new javax.swing.JLabel();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCalidadServicio = new javax.swing.JList<>();
        jCalidadServicio = new javax.swing.JLabel();
        jDatosViaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTitulo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        jTitulo.setText("EMPRESA DE TRANSPORTE INMACULADA");

        jDatosPersonales.setText("I. Ingreso de Datos:");

        jNombres.setText("Nombres:");

        jTipoDocumento.setText("Tipo de documento");

        jNDocumento.setText("Nº de documento");

        jGenero.setText("Género");
        jGenero.setToolTipText("");

        jTextFieldNombres.setText("Ingrese sus nombres");
        jTextFieldNombres.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombresActionPerformed(evt);
            }
        });
        jTextFieldNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombresKeyTyped(evt);
            }
        });

        jTextFieldNDocumento.setText("Ingrese su numero de documento");
        jTextFieldNDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNDocumentoActionPerformed(evt);
            }
        });
        jTextFieldNDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNDocumentoKeyTyped(evt);
            }
        });

        jComboBoxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "DNI", "Pasaporte" }));
        jComboBoxTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDocumentoActionPerformed(evt);
            }
        });

        buttonGroupSexo.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setText("Masculino");
        jRadioButtonMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMasculinoActionPerformed(evt);
            }
        });

        buttonGroupSexo.add(jRadioButtonFemenino);
        jRadioButtonFemenino.setText("Femenino");
        jRadioButtonFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemeninoActionPerformed(evt);
            }
        });

        jButtonRegistrar.setText("Resumen de datos");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Reiniciar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jServicioAdicional.setText("Servicio adicional");

        jCheckBoxAudifonos.setText("Audifonos");
        jCheckBoxAudifonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAudifonosActionPerformed(evt);
            }
        });

        jCheckBoxManta.setText("Manta");
        jCheckBoxManta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMantaActionPerformed(evt);
            }
        });

        jCheckBoxRevistas.setText("Revistas");
        jCheckBoxRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRevistasActionPerformed(evt);
            }
        });

        buttonGroupPiso.add(jRadioButtonPiso1);
        jRadioButtonPiso1.setText("1");

        buttonGroupPiso.add(jRadioButtonPiso2);
        jRadioButtonPiso2.setText("2");

        jPiso.setText("Piso");

        jOrigen.setText("Seleccionar origen");

        jDestino.setText("Seleccionar destino");

        jComboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Arequipa", "Lima", "Cajamarca", "Piura" }));
        jComboBoxOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrigenActionPerformed(evt);
            }
        });

        jComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Arequipa", "Lima", "Cajamarca", "Piura" }));

        jListCalidadServicio.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Económico", "Estándar", "VIP" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListCalidadServicio);

        jCalidadServicio.setText("Calidad del servico");

        jDatosViaje.setText("II. Datos del viaje");

        jLabel1.setText("Ingrese Fecha");

        jTextField1.setText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jServicioAdicional)
                                    .addComponent(jCalidadServicio))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxRevistas)
                                            .addComponent(jCheckBoxManta)
                                            .addComponent(jCheckBoxAudifonos)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPiso)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jRadioButtonPiso1)
                                .addGap(38, 38, 38)
                                .addComponent(jRadioButtonPiso2))
                            .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNombres)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNombres, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTipoDocumento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jGenero)
                                .addGap(38, 38, 38)
                                .addComponent(jRadioButtonMasculino)
                                .addGap(56, 56, 56)
                                .addComponent(jRadioButtonFemenino))
                            .addComponent(jComboBoxTipoDocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNDocumento)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNDocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDatosPersonales)
                            .addComponent(jDatosViaje))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDatosPersonales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTipoDocumento)
                    .addComponent(jNDocumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGenero)
                            .addComponent(jRadioButtonMasculino)
                            .addComponent(jRadioButtonFemenino))
                        .addGap(31, 31, 31)))
                .addComponent(jDatosViaje)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jOrigen)
                            .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDestino)
                            .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPiso)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonPiso1)
                                .addComponent(jRadioButtonPiso2)))
                        .addGap(51, 248, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalidadServicio))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jServicioAdicional)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxAudifonos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxManta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBoxRevistas)))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombresActionPerformed

    private void jComboBoxTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoDocumentoActionPerformed

    private void jRadioButtonMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMasculinoActionPerformed
      
    }//GEN-LAST:event_jRadioButtonMasculinoActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed

        if (jTextFieldNombres.getText().equals("")
    
                || jComboBoxTipoDocumento.getSelectedItem().equals("Seleccionar")
                || jTextFieldNDocumento.getText().equals("")
                || buttonGroupSexo.getSelection().equals(false)                
                || jTextField1.getText().equals("")
                || jComboBoxOrigen.getSelectedItem().equals("")
                || jComboBoxDestino.getSelectedItem().equals("")
                || jListCalidadServicio.getSelectedValue().equals("")
                || buttonGroupPiso.getSelection().equals(false))   {
            JOptionPane.showMessageDialog(null, "Complete todos los datos", "¡Advertencia!", JOptionPane.WARNING_MESSAGE);
        } else {
            if (jCheckBoxAudifonos.isSelected()) {
                items = items + "\n- Audifonos";
            }

            if (jCheckBoxManta.isSelected()) {
                items = items + "\n- Manta";
            }

            if (jCheckBoxRevistas.isSelected()) {
                items = items + "\n- Revistas";
            }

            JOptionPane.showMessageDialog(null, "\nNombres: " + jTextFieldNombres.getText().toUpperCase()

                    + "\nTipo doc.: " + jComboBoxTipoDocumento.getSelectedItem() +": "+ jTextFieldNDocumento.getText()
                    + "\nGénero: " + jRadioButtonMasculino.getText()
                    + "\nFecha de viaje: " + jTextField1.getText()
                    + "\nOrigen: " + jComboBoxOrigen.getSelectedItem()
                    + "\nDestino: " + jComboBoxDestino.getSelectedItem()
                    + "\nCalidad de servicio: " + jListCalidadServicio.getSelectedValue()
                    + "\nNumeri de piso: " + jRadioButtonPiso1.getText()
                    + "\nServicio adicional: " + items, "Datos registrados del pasaje: ", WIDTH, null);

            dispose();
            new Registro_Pasajero().setVisible(true);
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jCheckBoxMantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMantaActionPerformed
        
    }//GEN-LAST:event_jCheckBoxMantaActionPerformed

    private void jComboBoxOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOrigenActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        new Registro_Pasajero().setVisible(true);
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jCheckBoxAudifonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAudifonosActionPerformed
    
    }//GEN-LAST:event_jCheckBoxAudifonosActionPerformed

    private void jCheckBoxRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRevistasActionPerformed
    
    }//GEN-LAST:event_jCheckBoxRevistasActionPerformed

    private void jTextFieldNDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNDocumentoKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo números", "¡Advertencia!", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jTextFieldNDocumentoKeyTyped

    private void jTextFieldNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombresKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo letras", "¡Advertencia!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldNombresKeyTyped

    private void jRadioButtonFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemeninoActionPerformed
       
    }//GEN-LAST:event_jRadioButtonFemeninoActionPerformed

    private void jTextFieldNDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNDocumentoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        Registro_Pasajero RegistroPasajero = new Registro_Pasajero();
        RegistroPasajero.setVisible(true);

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registro_Pasajero().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPiso;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jCalidadServicio;
    private javax.swing.JCheckBox jCheckBoxAudifonos;
    private javax.swing.JCheckBox jCheckBoxManta;
    private javax.swing.JCheckBox jCheckBoxRevistas;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JComboBox<String> jComboBoxOrigen;
    private javax.swing.JComboBox<String> jComboBoxTipoDocumento;
    private javax.swing.JLabel jDatosPersonales;
    private javax.swing.JLabel jDatosViaje;
    private javax.swing.JLabel jDestino;
    private javax.swing.JLabel jGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListCalidadServicio;
    private javax.swing.JLabel jNDocumento;
    private javax.swing.JLabel jNombres;
    private javax.swing.JLabel jOrigen;
    private javax.swing.JLabel jPiso;
    private javax.swing.JRadioButton jRadioButtonFemenino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JRadioButton jRadioButtonPiso1;
    private javax.swing.JRadioButton jRadioButtonPiso2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jServicioAdicional;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldNDocumento;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JLabel jTipoDocumento;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
